apiVersion: v1
kind: Service
metadata:
  name: scaletest-app-service
  namespace: scaletest-app
  labels:
    app: scaletest-app
spec:
  selector:
    app: scaletest-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
